name: get_a_motel
description: A multi-tenant motel booking platform.
version: 1.0.0+1

environment:
  sdk: '>=3.1.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  
  # State Management
  flutter_riverpod: ^3.0.3
  riverpod_annotation: ^3.0.3
  
  # Navigation
  go_router: ^17.0.1
  
  # Networking
  dio: ^5.4.0
  
  # Firebase Auth
  firebase_core: ^4.3.0
  firebase_auth: ^6.1.3
  
  # UI & Forms
  flutter_form_builder: ^10.2.0
  form_builder_validators: ^11.2.0
  google_fonts: ^6.1.0
  
  # Utilities
  shared_preferences: ^2.2.2
  intl: ^0.20.2
  uuid: ^4.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  
  # Generation
  build_runner: ^2.4.7
  riverpod_generator: ^3.0.3
  
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
